### ISSUE TITLE
socket type should be http, tls, ssh or database

### ISSUE THREAD

**Issue by luongthanhlam** [borderzero/border0-cli#230]
Hello guys, 
I got the error when trying to create a tcp socket on my local
```
$ mysocketctl socket create \
        --type tcp \
        --name "my service at home"
400 {"error_message":"socket type should be http, tls, ssh or database"}
```
I'm not sure how to fix it.

**Comment by adrianosela** [comment]
Hey @luongthanhlam , could you share more about what are you trying to achieve? 

Note that if you are simply trying to expose a tcp service over border0, the socket type to use is "tls".

If you would like comprehensive product support, kindly shoot us an email at support@border0.com, or join the [border0 community slack channel](https://join.slack.com/t/border0community/shared_invite/zt-zbx586ls-x44z7I3POLPQfesRWnig7Q) and we'll do our best to help you in a timely manner.

🚀

**Comment by atoonk** [comment]
Hi @luongthanhlam +1 to what @adrianosela mentioned. For authenticated TCP sockets, you need TLS sockets. Unauthenticated TCP sockets aren't supported. Alco see https://docs.border0.com/docs/accessing-any-tcp-service for a how-to on TLS/TCP sockets.

**Comment by luongthanhlam** [comment]
Got it, thank you for your prompt response 👍
